### ISSUE TITLE
py.test fails with import error

### ISSUE THREAD

**Issue by kpcyrd** [juga0/dhcpcanon#31]
I'm probably doing something wrong here, I have this test case which basically just runs py.test inside the release tar ball:
```
check() {
  cd "${pkgname}-${pkgver}"
  py.test
}
```

and I get this error (the environment is clean, so dhcpcanon isn't installed yet and therefore can't be imported):
```
==> Starting check()...
ImportError while loading conftest '/build/dhcpcanon/src/dhcpcanon-0.8.5/tests/conftest.py'.
tests/conftest.py:6: in <module>
    from dhcpcanon.dhcpcap import DHCPCAP
E   ModuleNotFoundError: No module named 'dhcpcanon'
==> ERROR: A failure occurred in check().
```

This seems to be related to this answer: https://stackoverflow.com/a/46222631

**Comment by juga0** [comment]
> I'm probably doing something wrong here, I have this test case which basically just runs py.test inside the release tar ball:
> 
> ```
> check() {
>   cd "${pkgname}-${pkgver}"
>   py.test
> }
> ```
> 
> and I get this error (the environment is clean, so dhcpcanon isn't installed yet and therefore can't be imported):

Exactly, you need to first install it, if you're in virtualenv:

    pip install .
    pip install .[dev]  # to install development dependencies, as pytest

> ```
> ==> Starting check()...
> ImportError while loading conftest '/build/dhcpcanon/src/dhcpcanon-0.8.5/tests/conftest.py'.
> tests/conftest.py:6: in <module>
>     from dhcpcanon.dhcpcap import DHCPCAP
> E   ModuleNotFoundError: No module named 'dhcpcanon'
> ==> ERROR: A failure occurred in check().
> ```
> 
> This seems to be related to this answer: https://stackoverflow.com/a/46222631

**Comment by kpcyrd** [comment]
The problem was that I'm not running pip install since this is during packaging, but I managed to resolve it with:
```
PYTHONPATH=. py.test
```
Thanks though! :)
